In [1]:
import pandas as pd
pd.__version__

'1.4.2'

## Series对象

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

**指定索引**

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [6]:
# Series可以认为是一个特殊字典
dict = {
    'name': 'zhangsan',
    'age': 18
}
data = pd.Series(dict)
data

name    zhangsan
age           18
dtype: object

In [7]:
data['age']

18

**创建对象**

In [8]:
data = pd.Series(5, index=[range(10)])

In [9]:
data[0]

5

In [10]:
# 对象 只会保留 显示指定的对象
data = pd.Series({1:'a', 2:'b', 3:'c'}, index=[1, 2])
data

1    a
2    b
dtype: object

## DataFrame

In [11]:
word = pd.Series({1:"aaa", 2:"bbb", 3:"ccc"})
number = pd.Series({1:"32", 2:"22", 3:"22"})

In [12]:
frame = pd.DataFrame({'word': word, 'number': number})
frame

word number
1  aaa     32
2  bbb     22
3  ccc     22

In [13]:
frame.columns

Index(['word', 'number'], dtype='object')

**创建对象**

In [14]:
frame = pd.DataFrame(number, columns=['number'])
frame

number
1     32
2     22
3     22

In [15]:
data = [{'a':i, 'b': i*2} for i in range(4)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}, {'a': 3, 'b': 6}]

In [16]:
pd.DataFrame(data) # 字典列表创建方式

a  b
0  0  0
1  1  2
2  2  4
3  3  6

In [17]:
pd.DataFrame(pd.Series(data[0]), columns=['aaa'])

aaa
a    0
b    0

In [18]:
import numpy as np
pd.DataFrame(np.random.rand(3, 2), columns=['a', 'b'], index=[1, 2, 3])

a         b
1  0.543156  0.015404
2  0.605222  0.197129
3  0.610641  0.606341

**创建方式总结**

- 字典创建， value值要为Series对象
- 单个Series创建， 需要指定Colums
- 字典列表创建，每个key认为是一个colums
- 通过numpy的二维数组创建
- numpy的结构化数组创建，这个不想学了

**pandas的数组不可以修改，可以使用切片操作**

In [19]:
ind = pd.Index([2, 3, 4, 5, 6])
ind

Int64Index([2, 3, 4, 5, 6], dtype='int64')

In [20]:
ind[::2]

Int64Index([2, 4, 6], dtype='int64')

### 多级索引

In [21]:
# 使用元祖是多级索引的基础
index = [('a', 1), ('a', 11),('b', 1), ('b', 11), ('c', 1), ('c', 11)]
number = [11, 1, 22, 2, 33, 3]
data = pd.Series(number, index=index)
data

(a, 1)     11
(a, 11)     1
(b, 1)     22
(b, 11)     2
(c, 1)     33
(c, 11)     3
dtype: int64

In [22]:
# MultiIndex 
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('a',  1),
            ('a', 11),
            ('b',  1),
            ('b', 11),
            ('c',  1),
            ('c', 11)],
           )

In [23]:
data = data.reindex(index) # 重置索引

In [24]:
data

a  1     11
   11     1
b  1     22
   11     2
c  1     33
   11     3
dtype: int64

In [25]:
data[:, 1]

a    11
b    22
c    33
dtype: int64

In [26]:
data['a',:]

1     11
11     1
dtype: int64

### 将带行列索引的Series 转化为DataFrame

In [27]:
data_df = data.unstack()
data_df

1   11
a  11   1
b  22   2
c  33   3

In [28]:
data_df.stack()  # 反向转换

a  1     11
   11     1
b  1     22
   11     2
c  1     33
   11     3
dtype: int64

**多级索引的创建**

In [29]:
# 使用二维数组就可以
pd.DataFrame(np.random.rand(6,2), 
             index=[['a', 'a', 'b', 'b', 'c', 'd'], ['1', '2', '1', '2', '1', '1']], 
             columns=['data1', 'data2'])

data1     data2
a 1  0.476726  0.529105
  2  0.083599  0.980250
b 1  0.576931  0.328627
  2  0.995457  0.801505
c 1  0.680935  0.842578
d 1  0.086531  0.212518

In [30]:
# 如果将元组作为字典的键值 也是可以自动转化为 多级索引的
# 显式创建索引
index = pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'd'], ['1', '2', '1', '2', '1', '1']])
index

MultiIndex([('a', '1'),
            ('a', '2'),
            ('b', '1'),
            ('b', '2'),
            ('c', '1'),
            ('d', '1')],
           )

In [31]:
# 使用元组 创建多级索引
index = pd.MultiIndex.from_tuples([('a', '1'),
            ('a', '2'),
            ('b', '1'),
            ('b', '2'),
            ('c', '1'),
            ('d', '1')])
index

MultiIndex([('a', '1'),
            ('a', '2'),
            ('b', '1'),
            ('b', '2'),
            ('c', '1'),
            ('d', '1')],
           )

**使用笛卡尔积创建**

In [32]:
index = pd.MultiIndex.from_product( [['a', 'b'], [1, 2]], names=['en', 'num'])
index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['en', 'num'])

In [33]:
data = np.round(np.random.randn(4, 6), 1)
data

array([[-0.1, -0.6, -0.3,  2.7, -0.1,  2.9],
       [ 1.2,  1.2, -0.2, -1.4,  1.2,  1.5],
       [ 2.6,  1.7, -0.7,  0. , -1.2, -1.4],
       [-0.6, -0. , -0.4,  0.3,  0.3,  0.7]])

In [34]:
data[:, ::2] *= 10
data

array([[ -1. ,  -0.6,  -3. ,   2.7,  -1. ,   2.9],
       [ 12. ,   1.2,  -2. ,  -1.4,  12. ,   1.5],
       [ 26. ,   1.7,  -7. ,   0. , -12. ,  -1.4],
       [ -6. ,  -0. ,  -4. ,   0.3,   3. ,   0.7]])

In [35]:
data +=37
data

array([[36. , 36.4, 34. , 39.7, 36. , 39.9],
       [49. , 38.2, 35. , 35.6, 49. , 38.5],
       [63. , 38.7, 30. , 37. , 25. , 35.6],
       [31. , 37. , 33. , 37.3, 40. , 37.7]])

In [36]:
health_data = pd.DataFrame(data, index=index, columns=['q', 'w', 'e', 'r', 't', 'u'])
health_data

q     w     e     r     t     u
en num                                    
a  1    36.0  36.4  34.0  39.7  36.0  39.9
   2    49.0  38.2  35.0  35.6  49.0  38.5
b  1    63.0  38.7  30.0  37.0  25.0  35.6
   2    31.0  37.0  33.0  37.3  40.0  37.7

## 多级列索引

In [37]:
columns = pd.MultiIndex.from_product([['aa', 'bb'], ['q', 'w', 'e']])
columns

MultiIndex([('aa', 'q'),
            ('aa', 'w'),
            ('aa', 'e'),
            ('bb', 'q'),
            ('bb', 'w'),
            ('bb', 'e')],
           )

In [38]:
health_data.columns=columns
health_data

aa                bb            
           q     w     e     q     w     e
en num                                    
a  1    36.0  36.4  34.0  39.7  36.0  39.9
   2    49.0  38.2  35.0  35.6  49.0  38.5
b  1    63.0  38.7  30.0  37.0  25.0  35.6
   2    31.0  37.0  33.0  37.3  40.0  37.7

Series的多级索引 的基本索引是行索引
DataFrame的多级索引的 基本索引的列索引

#  合并数据集

## Concat 和 Append 操作

In [39]:
# 定义一个简单生成 df 的 函数
def make_df(cols, ind):
    data = {s: [str(s) + str(i) for i in ind] for s in cols}
    return pd.DataFrame(data, ind)
make_df('ABCD', range(3))

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

**numpy使用concatenate,pd使用concat类似**

**concat合并Series 和 DataFrame**

In [40]:
s1 = pd.Series(['a', 'b', 'c'], index=[1, 2, 3])
s2 = pd.Series(['c', 'd','e'], index=[4, 5, 6])
pd.concat([s1, s2])

1    a
2    b
3    c
4    c
5    d
6    e
dtype: object

In [41]:
df1 = make_df('abc', range(3))
df2 = make_df('abc', range(4, 6))
pd.concat([df1, df2])

a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
4  a4  b4  c4
5  a5  b5  c5

In [42]:
# 水平合并
df3 = make_df('edf', range(3))
pd.concat([df1, df3], axis=1) # 或者使用 axis='col'

a   b   c   e   d   f
0  a0  b0  c0  e0  d0  f0
1  a1  b1  c1  e1  d1  f1
2  a2  b2  c2  e2  d2  f2

**捕捉重复索引，如果出现则报错**

In [43]:
## 设置 verify_integrity = True
## 如果索引无关紧 ignore_index = True 会重新生成索引
## 设置 keys 生成多级索引
pd.concat([s1, s2], keys=['s1', 's2'])

s1  1    a
    2    b
    3    c
s2  4    c
    5    d
    6    e
dtype: object

**使用join合并**
- join='outer‘ 默认， 并集，缺失位置补充NAN
- join='inner' 交集， 只会显示 都存在的元素

使用append也可以合并，但是不同于pythonappend,它不会更新原来的值，返回一个新的合并对象。

## merge合并

**on设置合并的列**

**如果两个列名不相同，可以使用left_on和right_on选择列进行合并操作。但是会有两个列的数据完全相同，可以使用drop()删除该列**

**使用left_index和right_index合并索引，也可以使用join操作它是默认按照索引进行合并的**

- how='inner'默认连接方式， 只会交集
- how='outer'

**suffixes参数，可以设置重复列名，自定义后嘴**

In [44]:
!ls data-USstates

README.md            state-areas.csv
state-abbrevs.csv    state-population.csv


In [45]:
pop = pd.read_csv('data-USstates/state-population.csv')
areas = pd.read_csv('data-USstates/state-areas.csv')
abb = pd.read_csv('data-USstates/state-abbrevs.csv')

In [46]:
pop.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [47]:
areas.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [48]:
abb.head()  # 各个省份的缩写

state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [49]:
merged = pd.merge(pop, abb, how='outer', left_on='state/region', right_on='abbreviation')
merged.head()

state/region     ages  year  population    state abbreviation
0           AL  under18  2012   1117489.0  Alabama           AL
1           AL    total  2012   4817528.0  Alabama           AL
2           AL  under18  2010   1130966.0  Alabama           AL
3           AL    total  2010   4785570.0  Alabama           AL
4           AL  under18  2011   1125763.0  Alabama           AL

In [50]:
## 丢弃重复的值
merged = merged.drop('abbreviation', axis=1)
merged.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

**检查数据是否有缺失**

In [51]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

**检查缺失值**

In [52]:
merged[merged['population'].isnull()].head()

state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN

**查找还有哪些洲有人缺失**

In [53]:
merged.loc[merged['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [54]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

**将面积合并进来**

In [55]:
final = pd.merge(merged, areas, on='state', how='left')
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [56]:
final.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [57]:
final.loc[final['area (sq. mi)'].isnull(), 'state'].unique()

array(['United States'], dtype=object)

In [58]:
final['state'][final['area (sq. mi)'].isnull()].unique()

array(['United States'], dtype=object)

In [59]:
%timeit final.loc[final['area (sq. mi)'].isnull(), 'state'].unique()

201 µs ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [60]:
%timeit final['state'][final['area (sq. mi)'].isnull()].unique()

162 µs ± 11.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [61]:
final.dropna(inplace=True)
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [62]:
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [63]:
data2010.set_index('state', inplace=True)

In [64]:
data2010.head()  # 按州设置响应的 索引

state/region   ages  year  population  area (sq. mi)
state                                                          
Alabama              AL  total  2010   4785570.0        52423.0
Alaska               AK  total  2010    713868.0       656425.0
Arizona              AZ  total  2010   6408790.0       114006.0
Arkansas             AR  total  2010   2922280.0        53182.0
California           CA  total  2010  37333601.0       163707.0

In [65]:
density = data2010['population'] / data2010['area (sq. mi)']
density.sort_values(ascending=False, inplace=True) 

In [66]:
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64

**sort_values**
- ascending = False 表示 升序
- inplace = True 替换原来的数据

In [68]:
rng = np.random.RandomState(42)
s1 = pd.Series(rng.rand(5))
s1

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [69]:
s1.mean()

0.5623850983416314

**描述通用属性**

In [77]:
s1.describe()

count    5.000000
mean     0.562385
std      0.308748
min      0.156019
25%      0.374540
50%      0.598658
75%      0.731994
max      0.950714
dtype: float64

## GroupBy的使用

In [78]:
pop.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [79]:
pop.groupby("ages")['population'].sum()

ages
total      1.373259e+10
under18    3.444637e+09
Name: population, dtype: float64

**分组后进行遍历访问**

In [86]:
for (method, group) in pop.groupby('ages'):
    print("{0}  shape={1}".format(method, group.shape))

total  shape=(1272, 4)
under18  shape=(1272, 4)


**累计过滤、转换、应用**

In [89]:
rng = np.random.RandomState(0)
df = pd.DataFrame({
    'key': ['A', 'B', 'C', 'A', 'B', 'C'],
    'data1' : rng.randint(0, 10, 6),
    'data2': range(6)
})
df

key  data1  data2
0   A      5      0
1   B      0      1
2   C      3      2
3   A      3      3
4   B      7      4
5   C      9      5

**累计**

In [93]:
df.groupby('key').aggregate(['min', np.median, max]) # aggregate 总数 传数组

data1            data2           
      min median max   min median max
key                                  
A       3    4.0   5     0    1.5   3
B       0    3.5   7     1    2.5   4
C       3    6.0   9     2    3.5   5

In [94]:
df.groupby('key').aggregate({'data1': min, 'data2': max}) # aggregate 总数， 传字典

data1  data2
key              
A        3      3
B        0      4
C        3      5

**过滤操作**

In [106]:
def filter_func(x):
    return x['data1'].std() > 2  # A组的 标准差 小于2会被过滤
df.groupby('key').std()

data1    data2
key                   
A    1.414214  2.12132
B    4.949747  2.12132
C    4.242641  2.12132

In [107]:
df.groupby('key').filter(filter_func)

key  data1  data2
1   B      0      1
2   C      3      2
4   B      7      4
5   C      9      5

**转换**

In [110]:
df.groupby('key').transform(lambda x: x - x.mean()) # 减去均值， 实现标准化

data1  data2
0    1.0   -1.5
1   -3.5   -1.5
2   -3.0   -1.5
3   -1.0    1.5
4    3.5    1.5
5    3.0    1.5

**apply()方法**
- 对分组后的df进行操作

In [113]:
def apply_func(x):
    x['data1'] -= x['data1'].mean()  # 减去均值进行标准话
    return x
df.groupby('key').apply(apply_func)

key  data1  data2
0   A    1.0      0
1   B   -3.5      1
2   C   -3.0      2
3   A   -1.0      3
4   B    3.5      4
5   C    3.0      5

## 数据透视表

In [118]:
titanic = pd.read_csv('seaborn-data/titanic.csv')

In [119]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [122]:
# 使用性别， 船舱等级 分组，二维
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

**使用数据透视表**

In [124]:
titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

**操作字符**

In [125]:
data = pd.Series(['jack', 'Peter', 'mike'])
data

0     jack
1    Peter
2     mike
dtype: object

In [129]:
data.str.capitalize() # 所有字符首字母大写

0     Jack
1    Peter
2     Mike
dtype: object

**处理时间**

In [139]:
# 需要有时间的 数据类型才行
data = np.array('2010-10-05', dtype='datetime64[D]')
data

array('2010-10-05', dtype='datetime64[D]')

In [141]:
data + np.arange(5)

array(['2010-10-05', '2010-10-06', '2010-10-07', '2010-10-08',
       '2010-10-09'], dtype='datetime64[D]')

**Series 使用时间数据结构**

In [147]:
index = pd.DatetimeIndex(['2010-10-05', '2010-10-06', '2010-10-07', '2011-10-08',
       '2011-10-09'])

In [148]:
data = pd.Series([0, 1, 2, 3, 4], index=index)
data

2010-10-05    0
2010-10-06    1
2010-10-07    2
2011-10-08    3
2011-10-09    4
dtype: int64

In [149]:
data['2011']  ## 可以只查询 年份 非常好用

2011-10-08    3
2011-10-09    4
dtype: int64

# 高性能计算 eval() 和 query()

## 普通方式

In [155]:
df1, df2, df3, df4 = (pd.DataFrame(rng.rand(100_000, 100)) for i in range(4))
%timeit df1 + df2 + df3 + df4

75.2 ms ± 876 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [159]:
%timeit  pd.eval(df1 + df2 + df3 + df4)

78.7 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [160]:
%timeit pd.eval('df1 + df2 + df3 + df4')

75.6 ms ± 772 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


**eval() 支持加减乘除 运算**

- 使用@ 访问局部变量

**query() 实现的字符串代数式运算**

- 可以实现 过滤运算