## 标量
**小写字母，另外加上标量的空间**

In [5]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y

(tensor(5.), tensor(6.))

## 向量
**小写粗体字母表示**

In [7]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

## 矩阵
**使用大写字母粗体**

In [9]:
A = torch.arange(20).reshape(4, 5)
A, A.T

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  5, 10, 15],
         [ 1,  6, 11, 16],
         [ 2,  7, 12, 17],
         [ 3,  8, 13, 18],
         [ 4,  9, 14, 19]]))

## 张量
**大写字母表示**
任意数轴的表示的通用方法

In [12]:
X = torch.arange(20).reshape(2, 2, 5)
X

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]])

In [14]:
X.T.shape

torch.Size([5, 2, 2])

## 张量的运算
乘法称之为Hadamard积数学符号⊙
加法和乘法，**都是对应的每一项进行操作**

- 降低维度的操作
- 例如：sum求和函数
- 可以指定axis轴进行降维

In [15]:
X = torch.arange(10).reshape(2, 5)
X

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
X.sum(axis = 1)

tensor([10, 35])

In [17]:
X.sum(axis = 0)

tensor([ 5,  7,  9, 11, 13])

In [19]:
X = X.sum(axis = 0, keepdims=True) ## 可以保持维度
X.shape, X

(torch.Size([1, 5]), tensor([[ 5,  7,  9, 11, 13]]))

## 点积
**每一项相乘，然后累计取和**

In [44]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

## 矩阵向量积
一个矩阵 m*n 和 一个 n列向量相乘
得到 m 行的 点积和
- **mv**

In [43]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A, x, A.shape, x.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]))

In [41]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

## 矩阵乘法
- **mm**
不应该与哈达玛混淆

In [47]:
A = torch.arange(8).reshape(4, 2)
B = torch.arange(8).reshape(2, 4)
torch.mm(A, B)

tensor([[ 4,  5,  6,  7],
        [12, 17, 22, 27],
        [20, 29, 38, 47],
        [28, 41, 54, 67]])

# 范数
**向量范数是将向量映射到标量的函数f中**
常用范数
- L1 范数
- L2 范数

In [48]:
u = torch.tensor([3.0, -4.0])
u

tensor([ 3., -4.])

In [49]:
## 计算L2 范数  所有元素的平方和 开平方
torch.norm(u)

tensor(5.)

In [50]:
## 计算L1 范数 各个元素绝对值之和
torch.abs(u).sum()

tensor(7.)