In [2]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

numel()计算元素的总数，这里向量只有一个，所以等于shape

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
X.shape

torch.Size([3, 4])

In [8]:
X.numel()

12

创建两个三行四列的

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
torch.ones(3)

tensor([1., 1., 1.])

In [13]:
torch.randn(3, 4)

tensor([[-0.6293,  0.6241, -0.6620, -0.3289],
        [-1.7357, -1.1071,  0.3008,  0.0615],
        [ 1.6505,  0.2294, -0.0648,  0.2888]])

In [14]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

# 运算符号

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

这是exp 就是 e=2.7183.... 的x次幂

In [16]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

对于向量的拼接
上下拼接 0和 左右拼接1

In [17]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [18]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
X += Y

In [20]:
X, Y

(tensor([[ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [21]:
X.sum()

tensor(96.)

In [22]:
Y.sum()

tensor(30.)

# 广播机制

In [23]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

矩阵形状不同，进行加法操作。**由于a和b分别是 3×1 和 1×2 矩阵，如果让它们相加，它们的形状不匹配。 我们将两个矩阵广播为一个更大的 3×2 矩阵，如下所示：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。**

In [24]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 索引和切片

In [25]:
X

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])

In [26]:
X[-1], X[1:3]

(tensor([12., 12., 12., 12.]),
 tensor([[ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]))

修改第二行第三列元素值

In [27]:
X[1, 2] = 91
X

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7., 91., 11.],
        [12., 12., 12., 12.]])

In [28]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]])

第1,2行 第1,2列全部修改为11

In [29]:
X[0:2, 0:2] = 11
X

tensor([[11., 11., 12., 12.],
        [11., 11., 12., 12.],
        [12., 12., 12., 12.]])

# 节省内存

使用id获取Y的地址， 最后在使用id获取修改Y向量后的地址，最后比较两个向量的地址差别。

In [30]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [31]:
# 两个向量地址相同，看来并没有重新开辟内存创建元素。
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140471814678864
id(Z): 140471814678864


如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。

In [32]:
before = id(X)
X += Y
id(X) == before

True

In [33]:
before = id(X)
X[:] = X + Y
id(X) == before

True

产生一个与tensor形状相同的 tensor且里面元素全为0

# 转换为Python对象

In [34]:
X

tensor([[37., 35., 44., 42.],
        [35., 37., 42., 44.],
        [44., 42., 40., 38.]])

转化为numpy张量。 torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量。

In [37]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [38]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

如果多个元素，使用item会报错

In [39]:
b = torch.tensor([3, 2])